import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";
import type { Contract } from "./types";
import { contractParagraphs, contractSections } from "./contracts";
import { PdfStamp } from "./pdf-stamp";

const styles = StyleSheet.create({
  page: {
    padding: 44,
    paddingBottom: 65,
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.5,
    color: "#20251f",
  },
  header: {
    backgroundColor: "#171d20",
    color: "white",
    padding: 22,
    marginBottom: 22,
  },
  title: { fontSize: 21, marginBottom: 8 },
  heading: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 6,
  },
  footer: {
    marginTop: 24,
    fontSize: 8,
    lineHeight: 1.2,
    color: "#768079",
  },
  signatures: { marginTop: 28, paddingTop: 16, borderTop: "1 solid #ccd0c7" },
});

export function ContractDocument({ contract }: { contract: Contract }) {
  return (
    <Document
      title={`Software subscription agreement ${contract.id}`}
      author={contract.contractorName}
    >
      <Page size="A4" style={styles.page}>
        <Text
          fixed
          style={{
            position: "absolute",
            top: 806,
            left: 44,
            fontSize: 8,
            color: "#768079",
          }}
          render={({ pageNumber, totalPages }) =>
            `${contract.id} | Page ${pageNumber} of ${totalPages}`
          }
        />
        <PdfStamp title="AGREEMENT" label="Unsigned copy" />
        <View style={styles.header}>
          <Text style={styles.title}>SOFTWARE SUBSCRIPTION AGREEMENT</Text>
          <Text>{contract.productName}</Text>
          <Text>Reference: {contract.id}</Text>
          <Text>Unsigned agreement</Text>
        </View>
        {contractSections(contract).map((section) => (
          <View key={section.title}>
            <Text style={styles.heading} minPresenceAhead={30}>
              {section.title}
            </Text>
            {contractParagraphs(section.body).map((paragraph, index) => {
              const newline = paragraph.indexOf("\n");
              const hasHeading =
                (section.title === "5. Software terms of use" ||
                  section.title === "Schedule B - Product terms of use") &&
                newline > 0 &&
                newline < 90;
              return (
                <Text
                  key={index}
                  orphans={3}
                  widows={3}
                  style={{ marginBottom: 10 }}
                >
                  {hasHeading ? (
                    <>
                      <Text style={{ fontFamily: "Helvetica-Bold" }}>
                        {paragraph.slice(0, newline)}
                      </Text>
                      {paragraph.slice(newline)}
                    </>
                  ) : (
                    paragraph
                  )}
                </Text>
              );
            })}
          </View>
        ))}
        <View style={styles.signatures} wrap={false}>
          <Text
            style={{
              fontSize: 12,
              fontFamily: "Helvetica-Bold",
              marginBottom: 12,
            }}
          >
            Execution by authorized representatives
          </Text>
          <Text style={{ marginBottom: 12 }}>
            IN WITNESS WHEREOF, the Parties execute this Agreement as of the
            Effective Date stated above.
          </Text>
          <Text>Developer: {contract.contractorName}</Text>
          <Text>Name: _____________________________________________</Text>
          <Text>Title: ______________________________________________</Text>
          <Text>Signature: __________________________________________</Text>
          <Text>Date: ______________________________________________</Text>
          <Text style={{ marginTop: 18 }}>Client: {contract.clientName}</Text>
          <Text>Name: _____________________________________________</Text>
          <Text>Title: ______________________________________________</Text>
          <Text>Signature: __________________________________________</Text>
          <Text>Date: ______________________________________________</Text>
          <Text style={styles.footer}>Generated by Beez | {contract.id}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function downloadContractPdf(contract: Contract) {
  const blob = await pdf(<ContractDocument contract={contract} />).toBlob();
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `Contract-${contract.id.replace(/[^a-zA-Z0-9-]/g, "")}.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
